CREATE TABLE IF NOT EXISTS `books` (
  `id` int(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发生时间',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `user_id` int(10) NOT NULL DEFAULT '0' COMMENT '用户ID',
  `book_name` varchar(255) NOT NULL DEFAULT '' COMMENT '书名',
  `file_name` varchar(255) NOT NULL DEFAULT '' COMMENT '文件名',
  `curr_chapter` int(10) NOT NULL DEFAULT '0' COMMENT '当前章节',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='书' AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS `sets` (
  `id` int(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发生时间',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `user_id` int(10) NOT NULL DEFAULT '0' COMMENT '用户ID',
  `set_name` varchar(255) NOT NULL DEFAULT '' COMMENT 'SET名称',
  `has_child` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否有下级set，0=无；1=有',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='SET' AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS `cells` (
  `id` int(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发生时间',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `user_id` int(10) NOT NULL DEFAULT '0' COMMENT '用户ID',
  `set_id` int(10) NOT NULL DEFAULT '0' COMMENT 'SET ID，直属SET ID',
  `cell_name` varchar(255) NOT NULL DEFAULT '' COMMENT 'CELL名称',
  `uri` varchar(255) NOT NULL DEFAULT '' COMMENT '资源地址，url等',
  `read_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已读，0=未读；1=已读',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='CELL' AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS `set_cell` (
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发生时间',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `set_id` int(10) NOT NULL DEFAULT '0' COMMENT 'SET ID',
  `cell_id` int(10) NOT NULL DEFAULT '0' COMMENT 'CELL ID',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '状态，0=有效；1=无效'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='SET-CELL关联表' AUTO_INCREMENT=1;